const { GoogleGenerativeAI } = require('@google/generative-ai');

const genAI = new GoogleGenerativeAI(process.env.LLM_API_KEY);

const SYSTEM_PROMPT = `
You are GitGuard AI, a premium code review assistant. Your goal is to analyze code diffs and provide actionable, high-quality feedback.

Focus on:
1. **Security**: Identify vulnerabilities, injection risks, and insecure patterns.
2. **Bugs**: Spot logic errors, undefined variables, and edge case failures.
3. **Performance**: Recommend optimizations for speed and memory.
4. **Best Practices**: Suggest improvements for readability and maintainability.

Rules:
- Only comment on the code provided in the diff.
- Be concise and professional.
- For every issue, suggest a corrected code block using Markdown.
- If no issues are found, provide a brief positive summary of the changes.
- Format your response as a GitHub-flavored Markdown document.

---
*Note: This review was generated by **GitGuard AI**. Please verify code suggestions before applying.*
`;

/**
 * Sanitize AI output to prevent malicious code injection or formatting issues.
 */
const sanitizeAIResponse = (text) => {
  // Remove any potential script tags or HTML that shouldn't be there
  let cleaned = text.replace(/<script\b[^>]*>([\s\S]*?)<\/script>/gim, "");
  
  // Ensure we don't have broken markdown code blocks
  const codeBlocks = (cleaned.match(/```/g) || []).length;
  if (codeBlocks % 2 !== 0) {
    cleaned += "\n```"; // Close dangling code block
  }
  
  return cleaned;
};

/**
 * Analyze a code diff using Gemini Pro
 */
const analyzeDiff = async (diffContent) => {
  try {
    if (!process.env.LLM_API_KEY) {
      throw new Error('LLM_API_KEY is not configured');
    }

    const model = genAI.getGenerativeModel({ model: "gemini-1.5-pro" });

    const prompt = `${SYSTEM_PROMPT}\n\nAnalyze the following code diff and provide a comprehensive review:\n\n${diffContent}`;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();

    return sanitizeAIResponse(text);
  } catch (error) {
    console.error('Error analyzing diff with AI:', error.message);
    throw error;
  }
};

module.exports = {
  analyzeDiff,
};
