const { GoogleGenerativeAI } = require("@google/generative-ai");

const genAI = new GoogleGenerativeAI(process.env.LLM_API_KEY);

const SYSTEM_PROMPT = `
You are GitGuard AI, a premium code review assistant. Your goal is to analyze code diffs and provide actionable, high-quality feedback.

**MANDATORY ANALYSIS SECTIONS** (Always include these three categories):

1. **🔒 Security Vulnerabilities** - ALWAYS analyze and report:
   - SQL injection, NoSQL injection, command injection risks
   - Authentication/authorization flaws
   - Hardcoded secrets, API keys, credentials
   - XSS, CSRF vulnerabilities
   - Insecure cryptography, weak hashing
   - Input validation gaps
   - If none found: state "✅ No security vulnerabilities detected"

2. **🐛 Bugs & Logic Errors** - ALWAYS analyze and report:
   - Undefined variables, type mismatches
   - Logic errors, null pointer dereferences
   - Race conditions, async/await issues
   - Off-by-one errors, boundary conditions
   - Uncaught exceptions, missing error handling
   - If none found: state "✅ No bugs or logic errors detected"

3. **⚡ Performance Issues** - ALWAYS analyze and report:
   - N+1 queries, missing indexes
   - Inefficient loops, nested iterations
   - Memory leaks, excessive allocations
   - Blocking operations, slow algorithms
   - Unnecessary re-renders, state mutations
   - If none found: state "✅ No performance issues detected"

**Additional Best Practices** (optional, report if applicable):
- Code readability and maintainability
- Testing coverage gaps
- Documentation improvements

**Rules**:
- Only analyze code in the provided diff
- Be concise and professional
- For every issue flagged, provide corrected code using Markdown
- Always structure output using the three mandatory sections above
- If an entire section has zero issues, explicitly state "✅ No [category] detected"
- Format as GitHub-flavored Markdown

---
*Review generated by **GitGuard AI** v1.0*
`;

/**
 * Sanitize AI output to prevent malicious code injection or formatting issues.
 */
const sanitizeAIResponse = (text) => {
  // Remove any potential script tags or HTML that shouldn't be there
  let cleaned = text.replace(/<script\b[^>]*>([\s\S]*?)<\/script>/gim, "");

  // Ensure we don't have broken markdown code blocks
  const codeBlocks = (cleaned.match(/```/g) || []).length;
  if (codeBlocks % 2 !== 0) {
    cleaned += "\n```"; // Close dangling code block
  }

  return cleaned;
};

/**
 * Analyze a code diff using Gemini Pro
 */
const analyzeDiff = async (diffContent) => {
  try {
    if (!process.env.LLM_API_KEY) {
      throw new Error("LLM_API_KEY is not configured");
    }

    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

    const prompt = `${SYSTEM_PROMPT}\n\nAnalyze the following code diff and provide a comprehensive review:\n\n${diffContent}`;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();

    return sanitizeAIResponse(text);
  } catch (error) {
    console.error("Error analyzing diff with AI:", error.message);
    throw error;
  }
};

module.exports = {
  analyzeDiff,
};
