const SYSTEM_PROMPT = `
You are GitGuard AI, a premium code review assistant. Your goal is to analyze code diffs and provide actionable, high-quality feedback.

Focus on:
1. **Security**: Identify vulnerabilities, injection risks, and insecure patterns.
2. **Bugs**: Spot logic errors, undefined variables, and edge case failures.
3. **Performance**: Recommend optimizations for speed and memory.
4. **Best Practices**: Suggest improvements for readability and maintainability.

Rules:
- Only comment on the code provided in the diff.
- Be concise and professional.
- For every issue, suggest a corrected code block using Markdown.
- If no issues are found, provide a brief positive summary of the changes.
- Format your response as a GitHub-flavored Markdown document.

---
*Note: This review was generated by **GitGuard AI**. Please verify code suggestions before applying.*
`;

/**
 * Sanitize AI output to prevent malicious code injection or formatting issues.
 */
const sanitizeAIResponse = (text) => {
  let cleaned = text.replace(/<script\b[^>]*>([\s\S]*?)<\/script>/gim, "");

  const codeBlocks = (cleaned.match(/```/g) || []).length;
  if (codeBlocks % 2 !== 0) {
    cleaned += "\n```";
  }

  return cleaned;
};

/**
 * Analyze a code diff using DeepSeek's OpenAI-compatible chat API.
 */
const analyzeDiff = async (diffContent) => {
  try {
    if (!process.env.DEEPSEEK_API_KEY) {
      throw new Error("DEEPSEEK_API_KEY is not configured");
    }

    const response = await fetch("https://api.deepseek.com/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${process.env.DEEPSEEK_API_KEY}`,
      },
      body: JSON.stringify({
        model: process.env.DEEPSEEK_MODEL || "deepseek-chat",
        messages: [
          {
            role: "system",
            content: SYSTEM_PROMPT,
          },
          {
            role: "user",
            content: `Analyze the following code diff and provide a comprehensive review:\n\n${diffContent}`,
          },
        ],
        temperature: 0.2,
      }),
    });

    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(
        `DeepSeek API request failed: ${response.status} ${errorBody}`,
      );
    }

    const data = await response.json();
    const text = data?.choices?.[0]?.message?.content;

    if (!text) {
      throw new Error("DeepSeek API returned an empty response");
    }

    return sanitizeAIResponse(text);
  } catch (error) {
    console.error("Error analyzing diff with DeepSeek:", error.message);
    throw error;
  }
};

module.exports = {
  analyzeDiff,
};
